apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-azure-vote-front
spec:
  hosts:
    - "*"
  # - svc-azure-vote-front.azure-vote.svc.cluster.local
  http:
    - name: "azure-vote-v1-route"
      route:
        - destination:
            host: svc-azure-vote-front.azure-vote.svc.cluster.local
            subset: v1

    # - name: "azure-vote-v2-routes"
    #   match:
    #     - uri:
    #         prefix: "/wpcatalog"
    #     - uri:
    #         prefix: "/consumercatalog"
    #   rewrite:
    #     uri: "/newcatalog"
    #   route:
    #     - destination:
    #         host: svc-azure-vote-front.azure-vote.svc.cluster.local
    #         subset: v2
    #         port:
    #           number: 8080
    #       weight: 100
    #   timeout: 1s
    #   retries:
    #     attempts: 3
    #     perTryTimeout: 200ms
    #     retryOn: 5xx
